/* eslint-disable */
// This file is auto-generated by scripts/generate-sound-assets.js
// Do not edit manually.

export const SOUND_OPTIONS = [
  { id: "no-problem-notification-sound", label: "No Problem Notification Sound" },
  { id: "so-proud-notification", label: "So Proud Notification" },
  { id: "vopvoopvooop", label: "Vopvoopvooop" },
] as const;

export type SoundId = (typeof SOUND_OPTIONS)[number]['id'];

export const SOUND_ASSETS: Record<SoundId, any> = {
  "no-problem-notification-sound": require("../assets/sounds/no-problem-notification-sound.mp3"),
  "so-proud-notification": require("../assets/sounds/so-proud-notification.mp3"),
  "vopvoopvooop": require("../assets/sounds/vopvoopvooop.mp3"),
};
