import type { MarketplaceActiveOrder, MarketplaceHistoryResult, MarketplaceOrderDetail } from './contracts';

type DoorDashRow = Record<string, any>;
function amount(value: unknown) { if (typeof value === 'string') { const number = Number(value.replace(/[^0-9.-]/g, '')); return Number.isFinite(number) ? number : null; } if (value && typeof value === 'object' && typeof (value as { unitAmount?: unknown }).unitAmount === 'number') return (value as { unitAmount: number }).unitAmount / 100; return null; }
function display(value: unknown) { const number = amount(value); return number == null ? null : `A$${number.toFixed(2)}`; }
function timestamp(value: unknown) { if (typeof value === 'number') return value < 1_000_000_000_000 ? value * 1000 : value; if (typeof value === 'string') { const parsed = Date.parse(value); return Number.isNaN(parsed) ? 0 : parsed; } return 0; }

export function adaptDoorDashActive(payload: { orders?: DoorDashRow[] }) {
  const orders: MarketplaceActiveOrder[] = (payload.orders || []).map((order) => ({ orderId: order.orderId || '', workflowUuid: order.deliveryUuid || '', orderUuid: order.deliveryUuid || '', customerName: order.consumer?.informalName || order.consumer?.formalNameAbbreviated || 'Customer', salesTotal: order.orderValue?.displayString || '', requestedAt: order.deliveryTime || order.pickupTime || order.createdAt || '', courierName: order.dasher?.informalName || order.dasher?.formalNameAbbreviated || '', fulfillmentType: order.fulfillmentDetails?.fulfillmentType || '', orderChannel: order.orderSubStatus?.display || 'DoorDash', status: order.orderStatusDisplay || String(order.orderStatus || 'Active'), statusDescription: order.orderExperience || '' })).filter((order) => order.orderId && order.workflowUuid);
  return { orders, providerRows: (payload.orders || []).length, nextCursor: null };
}

export function adaptDoorDashHistory(payload: { orders?: DoorDashRow[] }, mode: 'history' | 'scheduled'): MarketplaceHistoryResult {
  return { provider: 'doordash', orders: (payload.orders || []).map((order) => ({ orderId: order.orderId || '', workflowUuid: order.deliveryUuid || '', orderUuid: order.deliveryUuid || '', customerName: order.consumer?.informalName || order.consumer?.formalNameAbbreviated || 'Customer', salesTotal: order.orderValue?.displayString || '', netPayout: '', requestedAt: mode === 'scheduled' ? order.deliveryTime || order.pickupTime || order.completedTime || '' : order.completedTime || order.deliveryTime || order.pickupTime || '', courierName: order.dasher?.informalName || order.dasher?.formalNameAbbreviated || '', fulfillmentType: order.fulfillmentDetails?.fulfillmentType || '', issueType: order.orderStatusDisplay || '', orderChannel: order.orderSubStatus?.display || 'DoorDash', isSubscriber: false, subscriptionPass: '' })).filter((order) => order.orderId && order.workflowUuid), nextCursor: null };
}

export function adaptDoorDashDetail(detail: DoorDashRow, workflowUuid: string): MarketplaceOrderDetail {
  const items = (detail.orders || []).flatMap((order: DoorDashRow) => (order.orderItems || []).map((item: DoorDashRow) => ({ name: item.name || 'Item', price: item.price?.displayString || display(item.price) || '', quantity: item.quantity || 1, specialInstructions: item.specialInstructions || '', customizations: (item.itemExtras || []).map((extra: DoorDashRow) => ({ name: extra.title || extra.name || 'Options', options: (extra.itemExtraOptionsList || (extra.itemExtraOptions ? [extra.itemExtraOptions] : [])).map((option: DoorDashRow) => ({ name: option.name || 'Option', quantity: option.quantity || 1, price: option.price?.displayString || display(option.price) })) })) })));
  const total = detail.orderTotal?.displayString || display(detail.orderTotal);
  const subtotal = detail.preTaxTotal?.displayString || display(detail.preTaxTotal) || total;
  const discountAmount = (detail.discountDetails || []).reduce((sum: number, entry: DoorDashRow) => sum + Math.abs(amount(entry.value?.displayString || entry.value) || 0), 0);
  const timeline = [[detail.estimatedPickupTime, 'ESTIMATED_PICKUP'], [detail.actualPickupTime, 'PICKED_UP'], [detail.quotedDeliveryTime, 'ESTIMATED_DELIVERY'], [detail.actualDeliveryTime, 'DELIVERED'], [detail.completedTime, 'COMPLETED']].filter(([value]) => Boolean(value)).map(([value, orderState]) => ({ changedAt: timestamp(value), orderState: String(orderState) }));
  return { provider: 'doordash', sourceName: 'DoorDash', workflowUuid, orderId: detail.orderId || '', orderUUID: detail.deliveryUuid || '', requestedAt: timestamp(detail.orderDate), completedAtTimestamp: detail.completedTime ? timestamp(detail.completedTime) : null, customerName: detail.consumer?.informalName || detail.consumer?.formalNameAbbreviated || 'Customer', customerPhone: null, customerAddress: detail.deliveryAddress?.printableAddress || null, courierName: detail.dasher?.informalName || detail.dasher?.formalNameAbbreviated || null, courierPhone: null, restaurantName: detail.storeName || 'Restaurant', subtotal, subtotalAmount: amount(subtotal), discountLabel: detail.promoRedemptionDetails?.[0]?.promotionTitle || (discountAmount > 0 ? 'Marketplace promo' : null), discount: discountAmount > 0 ? `A$${discountAmount.toFixed(2)}` : null, discountAmount, total, totalAmount: amount(total), netPayout: total || '', marketplaceFeeRate: null, fulfillmentType: detail.fulfillmentType || 'DOORDASH', orderJobState: detail.orderStatusDisplay || String(detail.orderStatus || 'Completed'), statusDescription: detail.orderExperience || 'DoorDash', checkoutInfo: [detail.preTaxTotal ? { key: 'pre_tax_total', amount: subtotal || '', label: 'Pre-tax total' } : null, detail.subtotal ? { key: 'subtotal', amount: detail.subtotal.displayString || display(detail.subtotal) || '', label: 'Subtotal' } : null, detail.orderTotal ? { key: 'order_total', amount: total || '', label: 'Order total' } : null].filter(Boolean), orderStateChanges: timeline, items };
}
