import type { MarketplaceHistoryOptions, MarketplaceOrderDetailMode, MarketplaceSessionBundle, MarketplaceTransport } from './contracts';
import { buildUberActivePayload } from './uber-active';

export type MarketplaceDateParts = { year: number; month: number; day: number };
type Range = { start: MarketplaceDateParts; end: MarketplaceDateParts };
const BROWSER_HEADERS = { priority: 'u=1, i', 'sec-ch-ua': '"Not=A?Brand";v="99", "Google Chrome";v="151", "Chromium";v="151"', 'sec-ch-ua-mobile': '?0', 'sec-ch-ua-platform': '"macOS"', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36' };
const FLAGS = '{"featureKey":"OrdersList","isMobile":"false","isEmbedded":"false","userCohort":"MEMBERSHIP_LESS_THAN_500","pageName":"orders","operationMetricsUDLFlowEnabled":"true","isUEMOperationMetricsConsistencyEnabled":"true"}';

function restaurant(cookies: string) { const id = cookies.match(/(?:^|;\s*)selectedRestaurant=([^;]+)/)?.[1]?.trim(); if (!id) throw new Error('Uber Eats request failed: missing selected restaurant'); return id; }
function headers(cookies: string, referer: string, featureFlags?: string) { return { accept: '*/*', 'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8', 'content-type': 'application/json', origin: 'https://merchants.ubereats.com', referer, ...BROWSER_HEADERS, 'sec-fetch-site': 'same-origin', 'x-csrf-token': 'x', ...(featureFlags ? { 'x-feature-flags': featureFlags } : {}), Cookie: cookies }; }
function localDate(parts: MarketplaceDateParts, end = false) { return `${parts.year}-${String(parts.month).padStart(2, '0')}-${String(parts.day).padStart(2, '0')}${end ? ' 23:59:59' : ' 00:00:00'}`; }
async function request(transport: MarketplaceTransport, operation: string, url: string, init: RequestInit) { const response = await transport({ url, init }); const payload = await response.json().catch(() => null); if (!response.ok) throw new Error(`Uber Eats ${operation} request failed (${response.status})`); return { payload, status: response.status }; }

export function createUberEatsClient(transport: MarketplaceTransport) {
  return {
    async getActive(session: MarketplaceSessionBundle, cursor?: string) {
      const body = buildUberActivePayload(session.cookies, cursor);
      return request(transport, 'active', 'https://merchants.ubereats.com/manager/api/getActiveOrders?localeCode=en-AU', { method: 'POST', headers: { ...headers(session.cookies, 'https://merchants.ubereats.com/manager/orders/active?dateRange=this_week', FLAGS), 'accept-language': 'en-AU,en-GB;q=0.9,en-US;q=0.8,en;q=0.7', 'cache-control': 'no-cache', pragma: 'no-cache' }, body: JSON.stringify(body), cache: 'no-store' });
    },
    async getHistory(session: MarketplaceSessionBundle, range: Range, options: MarketplaceHistoryOptions) {
      const restaurantUuid = restaurant(session.cookies);
      if ((options.mode ?? 'history') === 'scheduled') {
        const short = (date: MarketplaceDateParts) => `${date.year}-${String(date.month).padStart(2, '0')}-${String(date.day).padStart(2, '0')}`;
        const query = `query ordersV2($filters: Orders_OrdersFiltersInput!, $pagination: Orders_OrdersPaginationInput, $shouldEnableChargebackComms: Boolean, $operationMetricsUDLFlowEnabled: Boolean) { ordersV2(filters: $filters pagination: $pagination shouldEnableChargebackComms: $shouldEnableChargebackComms operationMetricsUDLFlowEnabled: $operationMetricsUDLFlowEnabled) { rows { orderId workflowUuid orderUuid salesTotal netPayout requestedAt deliveryTimeLocal courierName fulfillmentType issueType orderStatus orderChannel eater { name isEatsPassSubscriber subscriptionPass } } paginationResult { nextCursor } } }`;
        const body = { operationName: 'ordersV2', variables: { filters: { orderStatusFilter: [], search: '', dateRange: { start: short(range.start), end: short(range.end) }, locationConstraints: { cities: [], countries: [], locationUUIDs: [restaurantUuid] }, displayCurrencyCode: 'AUD', currentTab: 'scheduledOrders' }, pagination: { limit: 20, cursor: options.cursor || '', nextTable: 'liveOrders' } }, query };
        return request(transport, 'scheduled history', 'https://merchants.ubereats.com/manager/graphql?op=ordersV2', { method: 'POST', headers: headers(session.cookies, 'https://merchants.ubereats.com/manager/orders/scheduled'), body: JSON.stringify(body), cache: 'no-store' });
      }
      const body = { filters: { currentTab: '', displayCurrencyCode: '', locationConstraints: { cities: [], countries: [], locationUuids: [restaurantUuid] }, dateFilter: { startDate: localDate(range.start), endDate: localDate(range.end, true), lastUpdatedAt: '' }, isEatsPassSubscriber: false, search: null, orderIssuesV2: [], issueOrderStatusFilter: [], displayByocIssues: false }, sort: { sortColumn: 'SORT_COLUMN_ORDER_COMPLETED_AT', sortDirection: 'SORT_DIRECTION_DESC' }, pagingInfo: { cursor: options.cursor || '', limit: 20, nextTable: 'liveOrders' }, pagination: { cursor: options.cursor || '', nextTable: 'historyOrders', limit: 20 } };
      console.info('[marketplace]', { provider: 'uber_eats', operation: 'history-filter', mode: options.mode ?? 'history', dateRange: options.dateRange || 'TODAY', startDate: body.filters.dateFilter.startDate, endDate: body.filters.dateFilter.endDate });
      return request(transport, 'history', 'https://merchants.ubereats.com/manager/api/getHistoricOrders?localeCode=en-AU', { method: 'POST', headers: headers(session.cookies, `https://merchants.ubereats.com/manager/orders?restaurantUUID=${restaurantUuid}`, FLAGS), body: JSON.stringify(body), cache: 'no-store' });
    },
    async getOrderDetail(session: MarketplaceSessionBundle, workflowUuid: string, mode: MarketplaceOrderDetailMode = 'history') {
      const restaurantUuid = restaurant(session.cookies); const live = mode === 'live'; const key = live ? 'liveOrderDetails' : 'orderDetails';
      const query = live ? `query LiveOrderDetails($workflowUUID: ID!, $metadata: Orders_OrderDetailsMetadataInput) { liveOrderDetails(workflowUUID: $workflowUUID metadata: $metadata) { requestedAt orderId orderUUID completedAtTimestamp fulfillmentType marketplaceFeeRate netPayout eater { name phone deliveryAddress } courier { name phone } restaurant { name uuid } checkoutInfo { key amount label } issueSummary { orderJobState failureReason issueType } orderStateChanges { changedAt orderState } items { name price quantity specialInstructions customizations { name options { name quantity price } } } } }` : `query OrderDetails($workflowUUID: ID!, $metadata: Orders_OrderDetailsMetadataInput, $shouldEnableChargebackComms: Boolean, $detailsRequestedByRestaurantUUID: ID) { orderDetails(workflowUUID: $workflowUUID metadata: $metadata shouldEnableChargebackComms: $shouldEnableChargebackComms detailsRequestedByRestaurantUUID: $detailsRequestedByRestaurantUUID) { requestedAt orderId orderUUID completedAtTimestamp fulfillmentType marketplaceFeeRate netPayout eater { name phone deliveryAddress } courier { name phone } restaurant { name uuid } checkoutInfo { key amount label } issueSummaryV2 { orderJobState statusDescription } orderStateChanges { changedAt orderState } items { name price quantity specialInstructions customizations { name options { name quantity price } } } } }`;
      const variables = live ? { workflowUUID: workflowUuid, metadata: { isEatsPassSubscriber: true, locale: 'en-AU' } } : { workflowUUID: workflowUuid, metadata: { isEatsPassSubscriber: false, locale: 'en-GB' }, shouldEnableChargebackComms: true, detailsRequestedByRestaurantUUID: restaurantUuid };
      const result = await request(transport, 'order detail', `https://merchants.ubereats.com/manager/graphql?op=${live ? 'LiveOrderDetails' : 'OrderDetails'}`, { method: 'POST', headers: headers(session.cookies, live ? `https://merchants.ubereats.com/manager/orders/active/${workflowUuid}?restaurantUUID=${restaurantUuid}&activeOrder=1&detailsRequestedByRestaurantUUID=${restaurantUuid}` : `https://merchants.ubereats.com/manager/orders/${workflowUuid}?restaurantUUID=${restaurantUuid}`), body: JSON.stringify({ operationName: live ? 'LiveOrderDetails' : 'OrderDetails', variables, query }), cache: 'no-store' });
      return { ...result, detail: (result.payload as any)?.data?.[key] };
    },
  };
}
