import crypto from 'crypto';
import { NextRequest, NextResponse } from 'next/server';
import { createServiceRoleClient } from '@my-small-business/supabase/server';
import { generateMarketingEmail } from '@/lib/google-genai';
import { Resend } from 'resend';

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

export async function POST(request: NextRequest) {
  try {
    const authHeader = request.headers.get('authorization');
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return NextResponse.json({ error: 'Missing or invalid authorization header' }, { status: 401 });
    }

    const token = authHeader.split(' ')[1];
    const supabase = await createServiceRoleClient();

    const { data: { user }, error: userError } = await supabase.auth.getUser(token);
    if (userError || !user) {
      console.error('Auth error:', userError);
      return NextResponse.json({ error: 'Unauthorized - Invalid token' }, { status: 401 });
    }

    // Admin check
    const { data: profile, error: profileError } = await supabase
      .from('profiles')
      .select('role_slug')
      .eq('id', user.id)
      .single();

    if (profileError || !profile || profile.role_slug !== 'admin') {
      return NextResponse.json({ error: 'Forbidden - Admin access required' }, { status: 403 });
    }

    const body = await request.json();
    const {
      customers,
      discountPercentage,
      subject: customSubject,
      htmlBody: customHtmlBody,
    } = body as {
      customers: Array<{ id: string; name: string; email: string }>;
      discountPercentage: number;
      subject?: string;
      htmlBody?: string;
    };

    if (!Array.isArray(customers) || customers.length === 0) {
      return NextResponse.json({ error: 'No customers provided' }, { status: 400 });
    }
    if (typeof discountPercentage !== 'number') {
      return NextResponse.json({ error: 'Invalid discount percentage' }, { status: 400 });
    }
    if (!resend || !process.env.RESEND_API_KEY) {
      return NextResponse.json({ error: 'Email service is not configured' }, { status: 500 });
    }

    const storeName = process.env.NEXT_PUBLIC_STORE_NAME || 'Our Store';
    const emailFrom = process.env.EMAIL_FROM || 'no-reply@pappasfishnchips.com.au';
    const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000';
    const hmacSecret = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.RESEND_API_KEY || 'default_secret';

    const results = [];

    // Process customers sequentially to avoid rate limits (or could be chunked)
    for (const customer of customers) {
      try {
        if (!customer.email || !customer.id) {
          results.push({ customer, success: false, error: 'Missing email or id' });
          continue;
        }

        const couponCode = `VIP${discountPercentage}-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
        const storeLink = `${baseUrl}/order?coupon=${couponCode}&utm_source=auto_marketing&utm_medium=email&utm_campaign=ai_discount`;
        const unsubToken = crypto.createHmac('sha256', hmacSecret).update(customer.id).digest('hex');
        const unsubscribeLink = `${baseUrl}/unsubscribe?id=${customer.id}&token=${unsubToken}`;
        
        // 1. Create Coupon in database
        const startsAt = new Date();
        const endsAt = new Date(startsAt.getTime() + 7 * 24 * 60 * 60 * 1000); // 7 days

        const { error: couponError } = await supabase.from('coupons').insert({
          code: couponCode,
          title: `AI Marketing ${discountPercentage}% Off`,
          description: `Special discount generated by AI Marketing for ${customer.name}`,
          is_active: true,
          discount_type: 'percent',
          discount_value: discountPercentage,
          starts_at: startsAt.toISOString(),
          ends_at: endsAt.toISOString(),
          max_uses: 1,
          max_uses_per_user: 1,
          target_email: customer.email,
          user_id: customer.id,
        });

        if (couponError) {
          results.push({ customer, success: false, error: `Failed to create coupon: ${couponError.message}` });
          continue;
        }

        // Use custom overrides if provided or generate once if missing
        let finalSubject = customSubject || 'Special Offer Inside!';
        let bodyTemplate = customHtmlBody || `
          <p>Hi {{CUSTOMER_NAME}},</p>
          <p>Here is your ${discountPercentage}% off discount!</p>
          <p>Use code: <strong>{{COUPON_CODE}}</strong> at checkout.</p>
          <a href="{{STORE_LINK}}">Shop Now</a>
          <br><br><small><a href="{{UNSUBSCRIBE_LINK}}">Unsubscribe from marketing emails</a></small>
        `;

        // Replace placeholders
        const finalHtmlBody = bodyTemplate
          .replace(/\{\{CUSTOMER_NAME\}\}/gi, customer.name || 'Valued Customer')
          .replace(/\{\{COUPON_CODE\}\}/gi, couponCode)
          .replace(/\{\{STORE_LINK\}\}/gi, storeLink)
          .replace(/\{\{UNSUBSCRIBE_LINK\}\}/gi, unsubscribeLink);

        // 3. Send Email
        const { error: sendError } = await resend.emails.send({
          from: emailFrom,
          to: [customer.email],
          subject: finalSubject,
          html: finalHtmlBody,
        });

        if (sendError) {
          results.push({ customer, success: false, error: `Failed to send email: ${sendError.message}` });
          continue;
        }

        // 4. Update last_marketing_email_sent_at in profiles
        const { error: updateError } = await supabase
          .from('profiles')
          .update({ last_marketing_email_sent_at: new Date().toISOString() })
          .eq('id', customer.id);

        if (updateError) {
          console.warn(`Failed to update last_marketing_email_sent_at for ${customer.id}`, updateError);
        }

        results.push({ customer, success: true });
      } catch (err) {
        results.push({ customer, success: false, error: err instanceof Error ? err.message : 'Unknown error' });
      }
    }

    return NextResponse.json({ success: true, results });
  } catch (error) {
    console.error('Marketing send error:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
