import { StyleSheet } from 'react-native';
import { BRAND_COLORS } from '@/utils/brand';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f4f6f8' },
  header: { backgroundColor: BRAND_COLORS.header },
  headerTitle: { color: '#fff', fontWeight: '700' },
  body: { flex: 1, flexDirection: 'row', gap: 12, padding: 12 },
  bodyCompact: { flexDirection: 'column' },
  bodyPhone: { padding: 8, gap: 8 },
  menuPane: { flex: 1, backgroundColor: '#fff', borderRadius: 8, overflow: 'hidden' },
  menuPaneCompact: { flex: 1, minHeight: 0 },
  quickListButtonWrap: {
    position: 'absolute',
    left: 12,
    bottom: 12,
  },
  quickListButton: {
    borderRadius: 999,
    elevation: 3,
  },
  quickListButtonContent: {
    minHeight: 48,
    paddingHorizontal: 8,
  },
  menuHeader: {
    minHeight: 52,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    paddingHorizontal: 12,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  menuHeaderText: { flex: 1 },
  menuTitle: { color: '#111827', fontSize: 19, fontWeight: '800' },
  menuSubtitle: { color: '#6b7280', marginTop: 1 },
  backButton: { borderRadius: 8 },
  levelFooter: {
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 6,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    backgroundColor: '#fff',
  },
  levelFooterActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'nowrap',
  },
  levelFooterButton: {
    borderRadius: 10,
    flex: 1,
    minWidth: 0,
    alignSelf: 'center',
  },
  levelFooterQuickListButton: {
    borderRadius: 10,
    flex: 1,
    minWidth: 0,
    alignSelf: 'center',
  },
  levelFooterButtonContent: {
    minHeight: 52,
    paddingHorizontal: 16,
  },
  levelFooterButtonLabel: {
    fontSize: 14,
    fontWeight: '700',
  },
  groupScreen: { flex: 1 },
  tileGrid: { padding: 4, paddingBottom: 10 },
  searchBody: { flex: 1 },
  searchInput: { margin: 10, marginBottom: 0, backgroundColor: '#fff' },
  searchGrid: { padding: 4, paddingBottom: 10 },
  groupCard: {
    flex: 1,
    minHeight: 108,
    margin: 5,
    borderRadius: 8,
    backgroundColor: '#111827',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    borderWidth: 1,
    borderColor: '#243244',
  },
  groupCardText: { color: '#fff', fontSize: 18, fontWeight: '900', textAlign: 'center' },
  topSellersSection: {
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 10,
    backgroundColor: '#fff',
  },
  topSellersHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 6 },
  topSellersHeaderText: { flex: 1 },
  topSellersTitle: { color: '#111827', fontSize: 15, fontWeight: '900' },
  topSellersLoading: { color: '#6b7280', fontSize: 12, fontWeight: '700' },
  topSellersList: { gap: 8, paddingRight: 8 },
  topSellerCard: {
    width: 118,
    minHeight: 74,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
    padding: 8,
    justifyContent: 'space-between',
  },
  topSellerQuantityBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    minWidth: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#16a34a',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  topSellerName: { color: '#111827', fontSize: 13, fontWeight: '900', paddingRight: 22 },
  topSellerMeta: { color: '#6b7280', fontSize: 11, fontWeight: '700' },
  topSellersEmpty: { color: '#6b7280', fontSize: 13, fontWeight: '700', paddingVertical: 8 },
  productCard: {
    flex: 1,
    minHeight: 112,
    margin: 4,
    borderRadius: 8,
    backgroundColor: '#fff7ed',
    borderWidth: 1,
    borderColor: '#fed7aa',
    padding: 8,
    justifyContent: 'space-between',
  },
  productQuantityBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    zIndex: 2,
    minWidth: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#16a34a',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  productQuantityText: { color: '#fff', fontSize: 13, fontWeight: '900' },
  productNameArea: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
    paddingTop: 8,
    paddingBottom: 6,
  },
  productName: {
    color: '#111827',
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  productPricePill: {
    alignSelf: 'center',
    minWidth: 70,
    borderRadius: 8,
    backgroundColor: '#dc2626',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  productPricePillCustom: {
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.38)',
  },
  productPrice: {
    color: '#fff',
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '900',
    textAlign: 'center',
  },
  productCardCustomColor: { borderWidth: 1 },
  productCardCustomText: { color: '#fff' },
  emptyState: { padding: 30, alignItems: 'center' },
  emptyTitle: { color: '#6b7280', fontSize: 16, fontWeight: '700' },
  editorBody: { flex: 1, padding: 10 },
  removableBlock: {
    marginTop: 8,
    marginBottom: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#fecaca',
    backgroundColor: '#fff1f2',
    paddingHorizontal: 10,
    paddingTop: 18,
    paddingBottom: 10,
  },
  addonList: { flex: 1, marginTop: 8 },
  emptyAddonText: { color: '#6b7280', textAlign: 'center', paddingVertical: 24 },
  addonGroup: {
    marginTop: 8,
    marginBottom: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
    paddingHorizontal: 10,
    paddingTop: 18,
    paddingBottom: 10,
  },
  addonGroupLabel: {
    position: 'absolute',
    top: -9,
    left: 10,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 3,
    backgroundColor: '#1d4ed8',
  },
  removeGroupLabel: {
    backgroundColor: '#dc2626',
  },
  addonGroupTitle: { color: '#fff', fontSize: 13, lineHeight: 16, fontWeight: '900' },
  removeGroupTitle: { color: '#fff' },
  optionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  optionButton: {
    minHeight: 52,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    paddingHorizontal: 8,
    paddingVertical: 7,
    justifyContent: 'center',
  },
  optionButtonSelected: { backgroundColor: '#2563eb', borderColor: '#1d4ed8' },
  removeButtonSelected: { backgroundColor: '#dc2626', borderColor: '#b91c1c' },
  optionText: { color: '#111827', fontSize: 13, lineHeight: 16, fontWeight: '900', textAlign: 'center' },
  optionTextSelected: { color: '#fff' },
  optionPrice: { color: '#6b7280', fontSize: 12, marginTop: 2, fontWeight: '800', textAlign: 'center' },
  groupRequirementText: { color: '#374151', fontSize: 12, fontWeight: '800', marginBottom: 8, marginTop: 2 },
  editorActions: { flexDirection: 'row', gap: 10, paddingTop: 8 },
  editorActionButton: { flex: 1, borderRadius: 8 },
  checkoutPane: { flex: 1, backgroundColor: '#fff' },
  checkoutBody: { flex: 1 },
  checkoutContent: { flexGrow: 1, padding: 16, paddingBottom: 28 },
  checkoutForm: { maxWidth: 520, width: '100%', gap: 10 },
  checkoutFormFull: { width: '100%', gap: 14 },
  checkoutTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#fff',
  },
  checkoutSegmentedButtons: { flex: 1 },
  checkoutInput: { backgroundColor: '#fff' },
  discountCard: {
    minHeight: 58,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  discountCardActive: {
    borderColor: '#86efac',
    backgroundColor: '#f0fdf4',
  },
  discountCardText: {
    flex: 1,
  },
  discountCardTitle: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '700',
  },
  discountCardTitleActive: {
    color: '#15803d',
  },
  discountCardValue: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 3,
  },
  discountCardValueActive: {
    color: '#166534',
  },
  discountCardAmount: {
    color: '#2563eb',
    fontSize: 16,
    fontWeight: '900',
  },
  discountCardAmountActive: {
    color: '#16a34a',
  },
  discountPresetRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    width: '100%',
    marginTop: 14,
  },
  discountPresetChip: {
    minWidth: 72,
    minHeight: 48,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#f8fafc',
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  discountPresetChipActive: {
    borderColor: '#16a34a',
    backgroundColor: '#16a34a',
  },
  discountPresetChipText: {
    color: '#0f172a',
    fontSize: 16,
    fontWeight: '900',
  },
  discountPresetChipTextActive: {
    color: '#fff',
  },
  customerIdentityRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
  },
  customerIdentityField: {
    flex: 1,
  },
  customerCard: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    padding: 12,
    gap: 10,
    backgroundColor: '#fff',
  },
  customerCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  customerIdentityRowSingleLine: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 8,
  },
  customerHelperText: {
    marginTop: 2,
  },
  customerPhoneField: {
    flex: 1.05,
  },
  customerSearchButton: {
    borderRadius: 8,
    justifyContent: 'center',
  },
  customerSearchButtonContent: {
    minHeight: 56,
    paddingHorizontal: 4,
  },
  customerInputRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
  },
  customerPhoneInput: {
    flex: 1.15,
  },
  customerNameButton: {
    flex: 1,
    minHeight: 56,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    backgroundColor: '#f8fafc',
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  customerNameLabel: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '700',
  },
  customerNameValue: {
    color: '#0f172a',
    fontSize: 16,
    fontWeight: '800',
    marginTop: 3,
  },
  customerInlineState: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  customerAutocompleteList: {
    gap: 8,
  },
  customerSearchResultCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    borderWidth: 1,
    borderColor: '#dbeafe',
    borderRadius: 8,
    backgroundColor: '#f8fbff',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  customerSearchResultMain: {
    flex: 1,
    gap: 2,
  },
  customerSearchResultName: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
  },
  customerSearchResultMeta: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '700',
  },
  customerSearchResultStats: {
    alignItems: 'flex-end',
    gap: 2,
  },
  customerSearchResultStat: {
    color: '#1d4ed8',
    fontSize: 12,
    fontWeight: '800',
  },
  customerSummaryCompact: {
    borderRadius: 8,
    backgroundColor: '#f8fafc',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
  },
  customerSummaryTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  customerSummaryCaption: {
    flex: 1,
    color: '#475569',
    fontSize: 12,
    fontWeight: '800',
  },
  customerSummaryActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  customerSummaryActionLabel: {
    fontSize: 12,
    fontWeight: '800',
  },
  customerSummaryStatsRow: {
    flexDirection: 'row',
    gap: 6,
  },
  customerSummaryStatPill: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 1,
  },
  customerSummaryStatLabel: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  customerSummaryStatValue: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '900',
  },
  customerRewardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  customerRewardText: {
    flex: 1,
    color: '#475569',
    fontSize: 12,
    fontWeight: '700',
  },
  customerSearchDialog: {
    maxWidth: 680,
    width: '100%',
    alignSelf: 'center',
  },
  customerSearchHint: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 10,
    marginBottom: 8,
  },
  customerModalLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  customerSearchResultsScroll: {
    flex: 1,
  },
  customerSearchResultsList: {
    gap: 8,
    paddingBottom: 4,
    flexGrow: 1,
  },
  customerSearchEmpty: {
    color: '#64748b',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    paddingVertical: 20,
  },
  phoneTrigger: {
    minHeight: 56,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 9,
    justifyContent: 'center',
  },
  phoneTriggerLabel: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '700',
  },
  phoneTriggerValue: {
    color: '#0f172a',
    fontSize: 19,
    fontWeight: '900',
    marginTop: 3,
  },
  phoneTriggerPlaceholder: {
    color: '#94a3b8',
  },
  checkoutNoteInput: { minHeight: 84 },
  checkoutNoteInputLarge: { minHeight: 140 },
  checkoutSummaryCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#bbf7d0',
    backgroundColor: '#f0fdf4',
    padding: 14,
    gap: 4,
  },
  checkoutSummaryEyebrow: { color: '#166534', fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  checkoutSummaryTotal: { color: '#14532d', fontSize: 28, fontWeight: '900' },
  checkoutSummaryMeta: { color: '#166534', fontSize: 13, fontWeight: '700' },
  checkoutSectionTitle: { color: '#111827', fontSize: 15, fontWeight: '900' },
  lookupRow: { minHeight: 22, justifyContent: 'center' },
  lookupText: { color: '#6b7280', fontSize: 13, fontWeight: '700' },
  foundText: { color: '#16a34a', fontSize: 13, fontWeight: '800' },
  newText: { color: '#dc2626', fontSize: 13, fontWeight: '800' },
  errorText: { color: '#dc2626', fontSize: 13, fontWeight: '800' },
  newCustomerBadge: {
    borderRadius: 8,
    backgroundColor: '#fee2e2',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  newCustomerBadgeText: { color: '#b91c1c', fontSize: 12, fontWeight: '900' },
  pickupPanel: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    padding: 12,
    gap: 10,
    backgroundColor: '#f9fafb',
  },
  pickupModeRow: { flexDirection: 'row', gap: 8 },
  pickupModeButton: { flex: 1, borderRadius: 8 },
  deliveryPanel: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    padding: 12,
    gap: 10,
    backgroundColor: '#f8fafc',
  },
  deliverySuggestionList: { gap: 8 },
  deliverySuggestionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#dbeafe',
    borderRadius: 8,
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  deliverySuggestionTitle: { color: '#0f172a', fontSize: 15, fontWeight: '800' },
  deliverySuggestionMeta: { color: '#475569', fontSize: 13, marginTop: 2 },
  deliveryAddressCard: {
    borderWidth: 1,
    borderColor: '#bfdbfe',
    borderRadius: 8,
    backgroundColor: '#eff6ff',
    padding: 12,
    gap: 4,
  },
  deliveryAddressLine: { color: '#1e3a8a', fontSize: 15, fontWeight: '900' },
  deliveryAddressMeta: { color: '#1d4ed8', fontSize: 13, fontWeight: '700' },
  deliveryQuoteCard: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    backgroundColor: '#fff',
    padding: 12,
    gap: 8,
  },
  deliveryQuoteMeta: { color: '#475569', fontSize: 13, fontWeight: '700' },
  paymentPanel: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    padding: 12,
    gap: 10,
    backgroundColor: '#f9fafb',
  },
  paymentModeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  paymentModeButton: { flexGrow: 1, minWidth: 128, borderRadius: 8 },
  preOrderPanel: {
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 10,
    gap: 8,
  },
  preOrderBadge: {
    alignSelf: 'flex-start',
    color: '#b91c1c',
    backgroundColor: '#fee2e2',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: '900',
  },
  pickupTimeText: { color: '#111827', fontSize: 18, fontWeight: '900' },
  pickupPickerButtons: { flexDirection: 'row', gap: 8 },
  pickupPickerButton: { flex: 1, borderRadius: 8 },
  placeOrderButton: { borderRadius: 8, marginTop: 8 },
  discountTotalValue: {
    color: '#16a34a',
    fontWeight: '900',
  },
  secondaryActionsPanel: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    padding: 12,
    gap: 10,
    backgroundColor: '#fff',
  },
  secondaryActionsTitle: { color: '#111827', fontSize: 13, fontWeight: '900' },
  secondaryActionsRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  secondaryActionButton: { flexGrow: 1, borderRadius: 8 },
  cartPane: {
    width: '33%',
    minWidth: 350,
    maxWidth: 460,
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 12,
  },
  cartPaneCompact: { flex: 1, width: '100%', minWidth: 0, minHeight: 0, maxWidth: '100%' },
  checkoutPaneHost: { padding: 0, overflow: 'hidden' },
  cartHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 8 },
  cartTitle: { color: '#111827', fontSize: 20, fontWeight: '800', flex: 1 },
  clearCartButton: { borderRadius: 8 },
  cartList: { flex: 1 },
  emptyCart: { color: '#6b7280', textAlign: 'center', marginTop: 30 },
  cartRow: { borderBottomWidth: 1, borderBottomColor: '#f3f4f6', paddingVertical: 8 },
  cartItemHeader: { flexDirection: 'row', alignItems: 'flex-start' },
  cartItemText: { flex: 1 },
  cartItemTopLine: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  cartItemNameButton: { flex: 1, flexShrink: 1 },
  cartItemName: { flex: 1, color: '#111827', fontSize: 15, lineHeight: 18, fontWeight: '900' },
  cartItemPriceBlock: { minWidth: 56, alignItems: 'flex-end', flexShrink: 1 },
  cartItemPrice: { color: '#111827', fontSize: 15, fontWeight: '900', textAlign: 'right' },
  cartItemSecondaryPrice: { marginTop: 1, color: '#6b7280', fontSize: 11, fontWeight: '700', textAlign: 'right' },
  cartItemDetails: { marginTop: 4 },
  cartItemMeta: { color: '#2563eb', fontSize: 13, marginTop: 2, fontWeight: '700' },
  cartItemRemoved: { color: '#dc2626', fontSize: 13, marginTop: 2, fontWeight: '800' },
  cartItemNote: { color: '#6b7280', fontSize: 14, marginTop: 3 },
  cartControls: { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 6, marginTop: 8, flexWrap: 'wrap' },
  qtyStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    backgroundColor: '#f9fafb',
  },
  stepperButton: { margin: -4 },
  cartQuantity: { minWidth: 24, textAlign: 'center', fontSize: 16, fontWeight: '900' },
  cartActionButton: { borderRadius: 999 },
  totals: { paddingVertical: 12, gap: 8 },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between' },
  totalLabel: { color: '#6b7280', fontSize: 15 },
  totalValue: { color: '#111827', fontSize: 15, fontWeight: '700' },
  grandTotalLabel: { color: '#111827', fontSize: 20, fontWeight: '900' },
  grandTotalValue: { color: '#111827', fontSize: 22, fontWeight: '900' },
  quickOrderNoteButton: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    backgroundColor: '#f9fafb',
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  quickOrderNoteButtonSelected: {
    borderColor: '#047857',
    backgroundColor: '#ecfdf5',
  },
  quickOrderNoteButtonText: { flex: 1 },
  quickOrderNoteTitle: { color: '#6b7280', fontSize: 11, lineHeight: 13, fontWeight: '900' },
  quickOrderNoteTitleSelected: { color: '#047857' },
  quickOrderNoteValue: { color: '#111827', fontSize: 14, lineHeight: 17, fontWeight: '900', marginTop: 1 },
  quickOrderNoteValueSelected: { color: '#064e3b' },
  quickOrderNoteEdit: { color: '#2563eb', fontSize: 12, fontWeight: '900', flexShrink: 0 },
  quickOrderNoteEditSelected: { color: '#047857' },
  quickOrderNoteGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  quickOrderNoteChip: {
    width: '48%',
    minHeight: 52,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quickOrderNoteChipSelected: {
    borderColor: '#047857',
    backgroundColor: '#047857',
  },
  quickOrderNoteChipText: {
    color: '#111827',
    fontSize: 16,
    lineHeight: 19,
    fontWeight: '900',
    textAlign: 'center',
  },
  quickOrderNoteChipTextSelected: { color: '#fff' },
  checkoutButton: { borderRadius: 8, marginTop: 10 },
  quickActionsPanel: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  quickActionsTitle: { color: '#111827', fontSize: 13, fontWeight: '900', marginBottom: 6 },
  quickPaymentRow: { flexDirection: 'row', gap: 8 },
  quickPaymentButton: { flex: 1 },
  completeButton: { marginTop: 12 },
  checkoutPlaceholder: {
    flex: 1,
    padding: 16,
    gap: 12,
    backgroundColor: '#f8fafc',
  },
  checkoutPlaceholderTitle: { color: '#111827', fontSize: 20, fontWeight: '900' },
  checkoutPlaceholderText: { color: '#475569', fontSize: 14, lineHeight: 21 },
  smartpayDialog: { borderRadius: 8, backgroundColor: '#fff' },
  smartpayDialogText: { color: '#374151', fontSize: 14, lineHeight: 20 },
  smartpayAmount: { marginTop: 12, color: '#111827', fontSize: 28, fontWeight: '900', textAlign: 'center' },
  noteDialog: { backgroundColor: '#fff' },
  noteInput: { backgroundColor: '#fff', minHeight: 90 },
  dialogActionStack: { marginTop: 16, gap: 10 },
  discountPresetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
    marginBottom: 16,
  },
  discountPresetButton: {
    width: '30%',
    minHeight: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  discountPresetButtonText: {
    color: '#1d4ed8',
    fontSize: 18,
    fontWeight: '900',
  },
  discountInputGroup: {
    gap: 8,
    marginTop: 8,
  },
  overlayScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
    zIndex: 9999,
    elevation: 9999,
  },
  overlayCenter: {
    width: '100%',
    maxWidth: 920,
  },
  overlayTitle: {
    color: '#111827',
    fontSize: 24,
    fontWeight: '900',
    paddingLeft: 24,
    paddingTop: 18,
  },
  overlayBody: {
    paddingHorizontal: 24,
    paddingBottom: 24,
    paddingTop: 8,
  },
  textEntryDialog: {
    borderRadius: 16,
    backgroundColor: '#fff',
    width: '100%',
  },
  textEntryTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingTop: 4,
    paddingRight: 14,
  },
  textEntryCloseButton: {
    marginTop: 2,
    marginRight: -2,
  },
  textEntryHeaderRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
    marginBottom: 16,
  },
  textEntryDoneButton: {
    width: 120,
    borderRadius: 12,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textEntryDoneButtonDisabled: {
    backgroundColor: '#94a3b8',
  },
  textEntryDoneButtonText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '900',
  },
  textEntryDisplay: {
    flex: 1,
    minHeight: 72,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#dbeafe',
    backgroundColor: '#eff6ff',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  textEntryDisplayText: {
    color: '#0f172a',
    fontSize: 28,
    fontWeight: '900',
  },
  textEntryPlaceholder: {
    color: '#94a3b8',
  },
  textEntryKeyboard: {
    gap: 10,
  },
  textEntryKeyboardRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
  },
  textEntryKeyboardRowInset: {
    paddingHorizontal: 20,
  },
  textEntryKeyboardRowWideInset: {
    paddingHorizontal: 56,
  },
  textEntryKey: {
    flex: 1,
    minHeight: 62,
    maxWidth: 62,
    borderRadius: 12,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textEntryWideKey: {
    flex: 1.8,
    minHeight: 62,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textEntryActionKey: {
    flex: 1,
    minHeight: 62,
    maxWidth: 96,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textEntrySecondaryKey: {
    backgroundColor: '#fee2e2',
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  textEntryPrimaryKey: {
    backgroundColor: '#dbeafe',
    borderWidth: 1,
    borderColor: '#93c5fd',
  },
  textEntryActionKeyDisabled: {
    backgroundColor: '#e5e7eb',
    borderColor: '#cbd5e1',
  },
  textEntryKeyText: {
    color: '#0f172a',
    fontSize: 20,
    fontWeight: '900',
  },
  textEntryPrimaryKeyText: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '900',
  },
  phonePadDialog: {
    borderRadius: 16,
    backgroundColor: '#fff',
    width: '100%',
  },
  phonePadTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingTop: 4,
    paddingRight: 14,
  },
  phonePadCloseButton: {
    marginTop: 2,
    marginRight: -2,
  },
  phonePadDisplay: {
    flex: 1,
    minHeight: 72,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#dbeafe',
    backgroundColor: '#eff6ff',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  phonePadDisplayText: {
    color: '#0f172a',
    fontSize: 30,
    fontWeight: '900',
  },
  phonePadHeaderRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 10,
    marginBottom: 16,
  },
  phonePadDoneButton: {
    width: 120,
    borderRadius: 12,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  phonePadDoneButtonText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '900',
  },
  phonePadDoneButtonDisabled: {
    backgroundColor: '#94a3b8',
  },
  phonePadGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  phonePadKey: {
    width: '31%',
    minHeight: 68,
    borderRadius: 12,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  phonePadKeySecondary: {
    backgroundColor: '#fee2e2',
    borderColor: '#fecaca',
  },
  phonePadKeyPrimary: {
    backgroundColor: '#dbeafe',
    borderColor: '#93c5fd',
  },
  phonePadKeyDisabled: {
    backgroundColor: '#e5e7eb',
    borderColor: '#cbd5e1',
  },
  phonePadKeyText: {
    color: '#0f172a',
    fontSize: 24,
    fontWeight: '900',
  },
  addonSummaryBar: {
    marginTop: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#fff',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  addonSummaryText: { flex: 1, gap: 2 },
  addonSummaryTitle: { color: '#111827', fontSize: 14, fontWeight: '900' },
  addonSummaryMeta: { color: '#6b7280', fontSize: 12, fontWeight: '700' },
  addonSummaryButton: { borderRadius: 8 },
  quickListGrid: { paddingTop: 8, paddingBottom: 8 },
  quickListCard: {
    flex: 1,
    minHeight: 112,
    margin: 4,
    borderRadius: 8,
    borderWidth: 1,
    padding: 8,
    justifyContent: 'space-between',
  },
  quickListEmpty: { color: '#6b7280', fontSize: 15, lineHeight: 22 },
  phoneNavContainer: {
    backgroundColor: '#111827',
    paddingHorizontal: 12,
    paddingBottom: 8,
    paddingTop: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#1f2937',
  },
  phoneNavTabs: {
    flexDirection: 'row',
    backgroundColor: '#1f2937',
    borderRadius: 10,
    padding: 3,
    gap: 4,
  },
  phoneNavTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    gap: 6,
  },
  phoneNavTabActive: {
    backgroundColor: '#2563eb',
  },
  phoneNavTabText: {
    color: '#9ca3af',
    fontSize: 14,
    fontWeight: '800',
  },
  phoneNavTabTextActive: {
    color: '#ffffff',
  },
  phoneCartBadge: {
    backgroundColor: '#ef4444',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 1,
    minWidth: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  phoneCartBadgeText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '900',
  },
  phoneFloatingCartBar: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    right: 12,
    backgroundColor: '#1e293b',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    zIndex: 100,
  },
  phoneFloatingCartInfo: {
    flex: 1,
    gap: 2,
  },
  phoneFloatingCartTitle: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '900',
  },
  phoneFloatingCartSub: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '700',
  },
  phoneFloatingCartButton: {
    backgroundColor: '#16a34a',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
  },
  phoneFloatingCartButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  phoneCartHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingBottom: 8,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  phoneBackToMenuButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 8,
  },
});
